.PHONY:Default clean

Default:
	make -C lcd
	make -C usb
	make -C media
	make -C app
	@echo "-----------------------------------------------------------------" 
	@echo "                      Good job! ~(@^_^@)~" 
	@echo "-----------------------------------------------------------------" 

clean:
	make clean -C lcd
	make clean -C usb
	make clean -C media
	make clean -C app

